version: '3.8'
services:
  driver:
    build: .
    environment:
    - DRIVER_SYSROOT_DIR=/host
    image: inaccel/driver:${TAG:-latest}
    network_mode: host
    privileged: true
    volumes:
    - /:/host
