#!/bin/sh

# Copyright © 2018-2021 InAccel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[ ${DEBUG} ] && set -vx
set -eu

if [ -z ${INACCEL:-} ]; then
	SYSROOT_DIR=$(realpath ${DRIVER_SYSROOT_DIR:-/})

	DRIVER=$(mktemp --tmpdir=${SYSROOT_DIR})

	cp --force --preserve=all ${0} ${DRIVER}

	mount --bind /etc/resolv.conf $(realpath --canonicalize-missing --no-symlinks ${SYSROOT_DIR}/etc/resolv.conf)

	INACCEL=1 exec chroot ${SYSROOT_DIR} /$(realpath --relative-to=${SYSROOT_DIR} ${DRIVER}) ${@}
fi

rm --force ${0}

trap "umount /etc/resolv.conf" EXIT

################################################################################

${@}
