#!/bin/sh

# Copyright © 2018-2023 InAccel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[ ${DEBUG} ] && set -vx
set -eu

if [ -z ${INACCEL:-} ]; then
	spider() {
		wget --connect-timeout=1 --header="Metadata: true" --output-document=/dev/null --quiet --tries=1 ${@}
	}

	if spider "http://169.254.169.254/2009-04-04/dynamic"; then
		export CLOUD_PROVIDER=aws
	elif spider "http://169.254.169.254/metadata?api-version=2017-03-01&format=text"; then
		export CLOUD_PROVIDER=azure
	fi

	SYSROOT_DIR=$(realpath ${DRIVER_SYSROOT_DIR:-/})

	mount --bind /etc/resolv.conf $(realpath ${SYSROOT_DIR}/$(chroot ${SYSROOT_DIR} realpath /etc/resolv.conf))

	TMPDIR=$(mktemp --directory --tmpdir=${SYSROOT_DIR} inaccel.XXXXXXXXXX)

	chmod 0755 ${TMPDIR}

	cp ${0} ${TMPDIR}/init

	cat scripts/* >> ${TMPDIR}/init

	export TMPDIR=/$(realpath --relative-to=${SYSROOT_DIR} ${TMPDIR})

	INACCEL=1 exec chroot ${SYSROOT_DIR} ${TMPDIR}/init ${@}
fi

cd ${TMPDIR}

trap "rm -fr ${TMPDIR} ; umount /etc/resolv.conf" EXIT

# [<vendor>]:[<device>][:<class>] ...
devices() {
	for id in ${@}; do
		vendor=$(echo ${id} | cut -d : -f 1)
		device=$(echo ${id} | cut -d : -f 2)
		class=$(echo ${id} | cut -d : -f 3)

		for path in /sys/bus/pci/devices/*; do
			if grep -q 0x${vendor} ${path}/vendor && grep -q 0x${device} ${path}/device && grep -q 0x${class} ${path}/class; then
				return 0
			fi
		done
	done

	return 1
}

################################################################################
