#!/bin/sh

# Copyright © 2018-2021 InAccel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[ ${DEBUG} ] && set -vx
set -eu

if [ -z ${INACCEL:-} ]; then
	spider() {
		wget --connect-timeout=1 --header="Metadata: true" --output-document=/dev/null --quiet --tries=1 ${@}
	}

	if spider "http://169.254.169.254/2007-01-19/meta-data"; then
		export CLOUD_PROVIDER=aws
	elif spider "http://169.254.169.254/metadata?api-version=2017-03-01&format=text"; then
		export CLOUD_PROVIDER=azure
	fi

	SYSROOT_DIR=$(realpath ${DRIVER_SYSROOT_DIR:-/})

	mount --bind /etc/resolv.conf $(realpath ${SYSROOT_DIR}/$(chroot ${SYSROOT_DIR} realpath /etc/resolv.conf))

	TMPDIR=$(mktemp --directory --tmpdir=${SYSROOT_DIR} inaccel.XXXXXXXXXX)

	cp ${0} ${TMPDIR}/init

	cat scripts/* >> ${TMPDIR}/init

	export TMPDIR=/$(realpath --relative-to=${SYSROOT_DIR} ${TMPDIR})

	INACCEL=1 exec chroot ${SYSROOT_DIR} ${TMPDIR}/init ${@}
fi

chdir ${TMPDIR}

trap "rm --force --recursive ${TMPDIR} ; umount /etc/resolv.conf" EXIT

################################################################################
