name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: DRIVER_VERSION
        required: true
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          inaccel/driver:latest
          inaccel/driver:${{ github.event.inputs.version }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ## Docker images

          - `docker pull inaccel/driver:${{ github.event.inputs.version }}`
        tag_name: v${{ github.event.inputs.version }}
