name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: DRIVER_VERSION
        required: true
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        flavor: latest=true
        images: inaccel/driver
        labels: |
          org.opencontainers.image.authors=InAccel <info@inaccel.com>
          org.opencontainers.image.url=https://inaccel.com
          org.opencontainers.image.vendor=InAccel
        tags: ${{ github.event.inputs.version }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ## Docker images

          - `docker pull ${{ fromJSON(steps.meta.outputs.json).tags[0] }}`
        tag_name: v${{ steps.meta.outputs.version }}
